### ISSUE TITLE
--disable-tls-checks should use the sslversion option of cURL

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/CMSScanner#108]
As mentioned at https://github.com/wpscanteam/wpscan/issues/1380, the --disable-tls-checks should use the `sslversion` of cURL to try to use the lowest protocol possible.

Theoretically possible by setting `sslversion: :tlsv1` as a request params in Typhoeus (https://github.com/typhoeus/ethon/blob/c5c9c6e10114c9939642be522ab05432ca7ec5d2/lib/ethon/curls/options.rb#L434), however it seems that there is a bug in cURL preventing that: https://github.com/curl/curl/issues/4097

**Comment by cnotin** [comment]
I fixed it in cURL, see:
https://github.com/curl/curl/pull/4304

I reused your script:
```ruby
# connect_check.rb

require 'typhoeus'

def check_target(url, params = {})
  res = Typhoeus.get(url, params.merge(connecttimeout: 10))

  puts "#{res.effective_url} - #{res.code} #{res.return_message}"
end

target = ARGV[0]

puts 'Not disabled:'
check_target(target)

puts
puts 'Disabled:'
check_target(target, ssl_verifypeer: false, ssl_verifyhost: 0, sslversion: :tlsv1)
```

Here is what I get with standard libcurl and with the new version:
```console
# LD_LIBRARY_PATH=/root/tools/curl/lib/.libs ruby ~/test.rb https://tls-v1-0.badssl.com:1010/
Not disabled:
https://tls-v1-0.badssl.com:1010/ - 0 SSL connect error

Disabled:
https://tls-v1-0.badssl.com:1010/ - 200 No error
# ruby ~/test.rb https://tls-v1-0.badssl.com:1010/
Not disabled:
https://tls-v1-0.badssl.com:1010/ - 0 SSL connect error

Disabled:
https://tls-v1-0.badssl.com:1010/ - 0 SSL connect error
```

Fixed by PR #109
