### ISSUE TITLE
memory_usage fails on windows devices since it uses "ps" - A Linux / Mac command

### ISSUE THREAD

**Issue by Reelix** [wpscanteam/CMSScanner#114]
Line of code: https://github.com/wpscanteam/CMSScanner/blob/master/lib/cms_scanner/helper.rb#L11

Might want an OS-neutral, language-specific method of getting the processes memory usage.

**Comment by erwanlr** [comment]
Unfortunately, there is not a OS-neutral way to get that as far as I know. If you do, feel free to share/send PR.

**Comment by erwanlr** [comment]
v0.6.1 released.

Could you please try it ?

All you have to do is update the CMSScanner gem with `gem update cms_scanner`, then run wpscan as usual

**Comment by Reelix** [comment]
Using CMSScanner with WPScan

[Without sys-proctable](https://i.imgur.com/Zoxb92B.png)

Error message is there telling the user what to do, but very messily.

[After sys-proctable gem installation](https://i.imgur.com/zexM5Nl.png)

It doesn't seem to like 

> ruby\gems\2.6.0\gems\sys-proctable-1.2.2\lib\windows\sys\proctable.rb

Line 95

>     def self.ps(**kwargs)	

Being called with the pid

**Comment by erwanlr** [comment]
Unless you installed CMSScanner, and then uninstalled `sys-proctable`, the first scenario should not occur as the `sys-proctable` should be installed along with CMSScanner (https://github.com/wpscanteam/CMSScanner/blob/master/cms_scanner.gemspec#L32)

I've opened an issue related to the second one: https://github.com/schneems/get_process_mem/issues/38

**Comment by Reelix** [comment]
> Unless you installed CMSScanner, and then uninstalled sys-proctable, the first scenario should not occur as the sys-proctable should be installed along with CMSScanner

It seems as though it should, but if I go

> gem uninstall sys-proctable
> gem uninstall cms_scanner (Accept prompt)
> gem install cms_scanner
> wpscan

It still throws the error. Hopefully just a weird caching issue my side. Guess we wait for schneems now :)

**Comment by erwanlr** [comment]
That's weird then, if I remove the `ffi` and `cms_scanner` then install cms_scanner, `ffi` will be fetched and installed (as I am not on a windows platform)

```
$ gem install cms_scanner
Fetching ffi-1.11.1.gem
Fetching cms_scanner-0.6.1.gem
Building native extensions. This could take a while...
Successfully installed ffi-1.11.1
Successfully installed cms_scanner-0.6.1
2 gems installed
```

Could be caching issue, or `Gem.win_platform?` returning false for some reason ?. If you have the Interactive Ruby Shell (type `irb` in a terminal), could you run `Gem.win_platform?` please ?

Here is an example on MacOSX:
```
$ irb
2.6.5 :001 > Gem.win_platform?
 => false 
```

**Comment by Reelix** [comment]
[The result - Only cms_scanner gets installed](https://i.imgur.com/3U06zEM.png)

**Comment by erwanlr** [comment]
I just installed Ruby (2.6.5) on a Windows7 via https://rubyinstaller.org/downloads/, then installed wpscan and it worked:

![WPScan](https://user-images.githubusercontent.com/1668843/67895535-f3f41980-fb5a-11e9-80dc-00d47c884a93.png)

The error you have is weird, as it means that the pid given (which is by default `Process.pid`) is not a Numeric (such as Integer etc):
- https://github.com/djberg96/sys-proctable/blob/sys-proctable-1.1.5/lib/windows/sys/proctable.rb#L96
- https://github.com/schneems/get_process_mem/blob/5825b19bf082411e87b03a6a1c5c7bc2fb9996c2/lib/get_process_mem.rb#L48

So I wonder how previous stuff worked somehow where this error should have come up.

Even though https://github.com/wpscanteam/CMSScanner/pull/115 seemed to work for you (which, based on the above error, should not), it was not considering Linux method to get the memory via /proc/, as well as mixing stuff up (gem requirement, platform and loading error in a ruby file)

**Comment by Reelix** [comment]
After mass uninstalling all the dependencies and wpscan itself then reinstalling wpscan, it does indeed seem that the latest commit did indeed solve the issue! Congrats :D

**Comment by erwanlr** [comment]
Thank you for confirming! that's awesome :)
