### ISSUE TITLE
Usage docs ?

### ISSUE THREAD

**Issue by soullivaneuh** [wpscanteam/CMSScanner#18]
Hi,

I would like to experiment your gem and, if possible, take part of contribution.

Do you have some use docs any where ?

Thanks!

**Comment by adnanmueller** [comment]
Hey Guys, I'm in the same boat as Soullivaneuh is there any update on the doco?

**Comment by derimagia** [comment]
I realize this is an old thread but is there any update in this? I'm interested in making a similiar scanner for Drupal and wanted to see what was out there.

**Comment by erwanlr** [comment]
Will try to do a rake task to create the basic files that you would need to
start writing a scanner using the gem.

No ETA unfortunately.

2016-09-04 17:13 GMT+01:00 Dave Wikoff <notifications@github.com>:

**Comment by derimagia** [comment]
No problem, but is there a way to just see this in action? An example would work for me in the meantime (You mentioned a v3 repo, is this still up to date with CMSScanner?)

**Comment by erwanlr** [comment]
Unfortunately, I can not give you access the the v3 repo, even if this would be the best way to learn :/

I've put an example folder in the repo, you can start to play with it by doing:
```git clone https://github.com/wpscanteam/CMSScanner```
```cp -R CMSScanner/example /the-location-of-your-choice/```
```cd /the-location-of-your-choice/```
```git init```
```bundle install```
```rake install```

After that you will have a ```cmsscan``` command, which is the scanner. ```cmsscan -h``` to display the help.
You can then make any changes to the files (like to change the scanner name etc) and recreate the executable with ```rake install``` to take the changes into consideration.

This is quite far from what I wanted to do (initial idea was kind of like Ruby on Rails commands: cmsscanner create / cmsscanner generate controller etc), but I don't have time for such thing :/

Any question / issue please let me know

**Comment by erwanlr** [comment]
v3 released: https://github.com/wpscanteam/wpscan-v3

Have fun!
