### ISSUE TITLE
Create methods such as #info_icon #warning_icon etc to be used in views

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/CMSScanner#40]
Will be easier to use (rather than always write green('[+]') etc in views)

Also could be overridden in Scanners implementation to display different icon w/o having to override the CMSScanner views

**Comment by FireFart** [comment]
@erwanlr I used the following method in wpscan: https://github.com/wpscanteam/wpscan/commit/b931df654dad684a2947747ecdc708748c7c365c
critical, warning and notice methods
