### ISSUE TITLE
RobotTxt entries not unique

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/CMSScanner#42]
Duplicates are displayed in the entries of the robots (i.e /wp-include/, /wp-include/, /wp-admin/)

**Comment by FireFart** [comment]
Also fixed in wpscan v2:
https://github.com/wpscanteam/wpscan/commit/7ec095d7083208bf4f091223b9bf100fb127e660

**Comment by erwanlr** [comment]
Fixed in the 0.0.37.dev branch
