### ISSUE TITLE
Provide "cli-no-color" alias (American English)

### ISSUE THREAD

**Issue by DrMurx** [wpscanteam/CMSScanner#56]
While I appreciate the use of British English, we've probably 99.9% American English in computing. Having `cli-no-colour` as option is counter-intuitive, and I'd appreciate an alias `cli-no-color` for that. It's always nice to have the choice!

**Comment by ethicalhack3r** [comment]
Thanks for the suggestion, but we will promote the use of the Queen's English ;) the other 99% of computing is wrong :)

**Comment by ethicalhack3r** [comment]
Ah crap, I thought this was the wpscan repo.

I'll let @erwanlr decide on this one then :)

**Comment by DrMurx** [comment]
I'm not campaigning against BE (au contraire). But there's still https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by erwanlr** [comment]
Fixed in latest version
