### ISSUE TITLE
avoid ```git ls-files``` in gemspec

### ISSUE THREAD

**Issue by blshkv** [wpscanteam/CMSScanner#64]
it fails to install if git is not installed. Here is a random example with more details:
https://github.com/jfelchner/ruby-progressbar/issues/54

**Comment by erwanlr** [comment]
Good spot, I am currently updating all our gems to reflect that, as well as the typo you spotted

**Comment by erwanlr** [comment]
All our gems have been updated & new versions released to reflect the changes.

Thank you again!

**Comment by blshkv** [comment]
Great, thanks a lot!
