### ISSUE TITLE
v0.0.40.1 missing gemspec and other files

### ISSUE THREAD

**Issue by blshkv** [wpscanteam/CMSScanner#66]
There are no LICENSE README.md and cms_scanner.gemspec files in the archive.
I'm not sure if it was done in purpose.

**Comment by erwanlr** [comment]
For the .gemspec, yes it was done on purpose, as it doesn't seem to be needed in the archive, and I can't find any reference of it being required (let me know if you do/did though)

**Comment by blshkv** [comment]
Ok, not an issue here, was just curious :) thanks!
